import Slide from "components/motion/Slide";
import Card from "components/portfolio/Card";
import Head from "next/head";
import { FiChevronDown } from "react-icons/fi";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="overflow-hidden max-w-screen h-screen 
      flex flex-col flex-wrap justify-center p-4 
      bg-gradient-to-tr from-pink-200 to-white "
      >
        <Slide direction="right" className="my-auto">
          <span
            className="flex flex-col items-end 
        text-transparent bg-gradient-to-tr from-gray-900 to-indigo-900 
        bg-clip-text mix-blend-multiply"
          >
            <h1 className="text-7xl font-extrabold">George Manning</h1>
            <h2 className="text-3xl font-extrabold">Full Stack Developer</h2>
          </span>
        </Slide>
        <FiChevronDown size={48} className="place-self-center animate-bounce" />
      </div>
      <div
        className="overflow-hidden  min-h-screen 
      flex justify-center py-4 
      bg-gradient-to-bl from-indigo-900 to-gray-600 "
      >
        <div className="overflow-hidden w-screen 
        gap-y-4 xl:w-7/12 
        flex flex-col flex-wrap justify-around
        ">
          <h1 className="text-3xl text-gray-100 px-4">Projects </h1>
          <Slide direction="right">
            <Card />
          </Slide>

          <Slide direction="right" delay={0.3}>
            <Card />
          </Slide>
          <Slide direction="right" delay={0.7}>
            <Card />
          </Slide>
          <Slide direction="right" delay={1}>
            <Card />
          </Slide>
        </div>
      </div>
      <div
        className="overflow-hidden  h-screen 
      flex justify-center p-4 
      bg-gradient-to-bl from-gray-200 to-white "
      >
        <div className="overflow-hidden w-screen xl:w-7/12 flex flex-col justify-start py-4">
          <h1 className="text-4xl font-extrabold">Contact</h1>
          <div className="h-full w-full flex flex-col items-center justify-evenly">
          <p>Email</p>
          <p>Github</p>
          </div>
        </div>
      </div>
    </>
  );
}
